- name: Shell playbook
  hosts: localhost
  become: true

  tasks:
    - name: Install Fira Code Fonts
      apt:
        name: fonts-firacode
        state: present

    - name: Install ripgrep package
      apt:
        name: ripgrep
        state: present

    - name: Install tree package
      apt:
        name: tree
        state: present

    - name: Install starship shell prompt
      shell: snap install starship --edge
      args:
        creates: /usr/local/bin/starship
      changed_when: false

    - name: Install jump
      snap:
        name: jump
        classic: yes
        state: present

    - name: Install fzf package
      apt:
        name: fzf
        state: present

