---
- name: Install Developer Tools
  hosts: localhost
  become: true

  tasks:
    - name: Add Microsoft GPG key for Visual Studio Code
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add Microsoft repository for Visual Studio Code
      apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        state: present

    - name: Install Visual Studio Code
      apt:
        name: code
        state: present

    - name: Install 1Password
      snap:
        name: 1password
        state: present

    - name: Install Terraform
      snap:
        name: terraform
        classic: yes
        channel: latest/beta
        state: present

    - name: Install Poetry
      shell: curl -sSL https://install.python-poetry.org | python3 -
      args:
        creates: /usr/local/bin/poetry
      changed_when: false

    - name: Install Astro CLI
      shell: curl -sSL https://install.astronomer.io | sudo bash
      args:
        creates: /usr/local/bin/astro
      changed_when: false

    - name: Install Slack
      snap:
        name: slack
        state: present

    - name: Install Starship prompt
      snap:
        name: starship
        classic: yes
        state: present

    - name: Install PyCharm Community Edition
      snap:
        name: pycharm-community
        classic: yes
        state: present
    
    - name: Install Spotify
      snap:
        name: spotify
        classic: yes
        state: present

